#!/usr/bin/env bash

sudo dpkg --add-architecture i386
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install unzip lib32z1 lib32ncurses5 lib32gcc1 lib32stdc++6 libcurl3-gnutls:i386 git curl

sudo loginctl enable-linger ubuntu
mkdir -p .config/systemd/user/

# Random fix to get sysmted user services working:
echo 'export XDG_RUNTIME_DIR=/run/user/`id -u`' >> ~ubuntu/.profile
cp .profile .bash_profile
export XDG_RUNTIME_DIR=/run/user/`id -u`

# all from https://wiki.teamfortress.com/wiki/Linux_dedicated_server
mkdir ./hlserver && cd hlserver
wget http://media.steampowered.com/installer/steamcmd_linux.tar.gz
tar zxf steamcmd_linux.tar.gz
rm steamcmd_linux.tar.gz

cat <<EOF >tf2_ds.txt
login anonymous
force_install_dir ./tf2
app_update 232250
quit
EOF

cat <<EOF >update.sh
#!/bin/sh
./steamcmd.sh +runscript tf2_ds.txt
EOF
chmod +x update.sh

# seems like we need to "prime" steamcmd by running it once..
echo quit | ./steamcmd.sh

# now download TF2 Dedicated Server
./update.sh

MMOD_BASE="https://mms.alliedmods.net/mmsdrop/1.11/"
LATEST_MMOD=$(curl "${MMOD_BASE}"mmsource-latest-linux)
wget -O mmsource.tar.gz "${MMOD_BASE}${LATEST_MMOD}"
tar xzvf mmsource.tar.gz -C tf2/tf/
rm mmsource.tar.gz

SMOD_BASE="https://sm.alliedmods.net/smdrop/1.11/"
LATEST_SMOD=$(curl "${SMOD_BASE}"sourcemod-latest-linux)
wget -O sourcemod.tar.gz "${SMOD_BASE}${LATEST_SMOD}"
tar xzvf sourcemod.tar.gz -C tf2/tf/
rm sourcemod.tar.gz

wget http://tftrue.esport-tools.net/TFTrue.zip
unzip TFTrue.zip -x Readme.txt -d tf2/tf/
rm TFTrue.zip

mkdir cfgs
cd cfgs/
git init
git remote add -f origin https://github.com/mkrl/cfgtf
git config core.sparseCheckout true
echo "server/cfg/" >> .git/info/sparse-checkout
git pull origin master
cd server/cfg/
cp ugc/* oz/* etf2l/* -t ~ubuntu/hlserver/tf2/tf/cfg/

cd

for i in {1..4}; do
  cat <<EOF > ~ubuntu/hlserver/tf2/tf/cfg/server-$i.cfg
rcon_password abcdef
EOF

  cat <<EOF > ~ubuntu/hlserver/tf2-$i.sh
#!/bin/sh
tf2/srcds_run -console -game tf +sv_pure 1 +map cp_badlands -strictportbind +maxplayers 12 +servercfgfile server-$i.cfg
EOF
  chmod +x ~ubuntu/hlserver/tf2-$i.sh

  cat <<EOF > ~ubuntu/.config/systemd/user/tf2-$i.service
[Unit]
Description=TF2-$i

[Service]
Type=simple
WorkingDirectory=/home/ubuntu/hlserver/
ExecStart=/home/ubuntu/hlserver/tf2-$i.sh

[Install]
WantedBy=default.target
EOF
done

systemctl --user daemon-reload
systemctl --user enable tf2-1

sync
